<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class PropertiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('properties')->insert([



            // Propiedad 1 - para Agent 4
            [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Imi',
                'property_slug' => 'imi',
                'property_code' => 'PC001',
                'property_status' => 'compra',
                'lowest_price' => '4300000',
                'max_price' => '4500000',
                'property_thambnail' => 'upload/property/thambnail/p1t.png',
                'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas',
                'long_descp' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ornare arcu odio ut sem nulla pharetra. Suspendisse interdum consectetur libero id. Sit amet commodo nulla facilisi nullam. Integer vitae justo eget magna fermentum iaculis eu non diam. Nibh ipsum consequat nisl vel pretium lectus. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Pretium vulputate sapien nec sagittis aliquam malesuada. Tortor condimentum lacinia quis vel eros. Nulla facilisi nullam vehicula ipsum. Facilisis magna etiam tempor orci eu lobortis elementum. Sed vulputate odio ut enim blandit. Auctor urna nunc id cursus metus aliquam eleifend mi. Ut sem viverra aliquet eget sit amet tellus. Elit sed vulputate mi sit amet mauris commodo.</p>',
                'bedrooms' => '4',
                'bathrooms' => '3',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'Imi, Campeche, Campeche, Colonia Imi, C.P. 24560',
                'city' => 'Campeche',
                'state' => '4',
                'postal_code' => '24560',
                'neighborhood' => 'Quinta Don Nacho',
                'latitude' => '19.871107',
                'longitude' => '-90.474048',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '4',
                'status' => '1',
                'created_at' => '2023-07-01 12:53:34',
            ],

            // Propiedad 2 - para Agent 5
            [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Nogales',
                'property_slug' => 'nogales',
                'property_code' => 'PC002',
                'property_status' => 'compra',
                'lowest_price' => '6250300',
                'max_price' => '6555000',
                'property_thambnail' => 'upload/property/thambnail/p2t.png',
                'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas',
                'long_descp' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ornare arcu odio ut sem nulla pharetra. Suspendisse interdum consectetur libero id. Sit amet commodo nulla facilisi nullam. Integer vitae justo eget magna fermentum iaculis eu non diam. Nibh ipsum consequat nisl vel pretium lectus. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Pretium vulputate sapien nec sagittis aliquam malesuada. Tortor condimentum lacinia quis vel eros. Nulla facilisi nullam vehicula ipsum. Facilisis magna etiam tempor orci eu lobortis elementum. Sed vulputate odio ut enim blandit. Auctor urna nunc id cursus metus aliquam eleifend mi. Ut sem viverra aliquet eget sit amet tellus. Elit sed vulputate mi sit amet mauris commodo.</p>',
                'bedrooms' => '4',
                'bathrooms' => '3',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'nogales, Colonia Hipódromo Dos, C.P. 22195',
                'city' => 'Tijuna',
                'state' => '2',
                'postal_code' => '22195',
                'neighborhood' => 'La presa',
                'latitude' => '32.494760',
                'longitude' => '-116.984320',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '5',
                'status' => '1',
                'created_at' => '2023-07-02 12:53:34',
            ],

            // Propiedad 3 - para Agent 6
            [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Tiburón Los Cangrejos',
                'property_slug' => 'tiburon-los-cangrejos',
                'property_code' => 'PC003',
                'property_status' => 'compra',
                'lowest_price' => '2310000',
                'max_price' => '2490000',
                'property_thambnail' => 'upload/property/thambnail/p3t.png',
                'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas',
                'long_descp' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ornare arcu odio ut sem nulla pharetra. Suspendisse interdum consectetur libero id. Sit amet commodo nulla facilisi nullam. Integer vitae justo eget magna fermentum iaculis eu non diam. Nibh ipsum consequat nisl vel pretium lectus. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Pretium vulputate sapien nec sagittis aliquam malesuada. Tortor condimentum lacinia quis vel eros. Nulla facilisi nullam vehicula ipsum. Facilisis magna etiam tempor orci eu lobortis elementum. Sed vulputate odio ut enim blandit. Auctor urna nunc id cursus metus aliquam eleifend mi. Ut sem viverra aliquet eget sit amet tellus. Elit sed vulputate mi sit amet mauris commodo.</p>',
                'bedrooms' => '4',
                'bathrooms' => '2',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'cabo San Lucas, Colonia Los Cangrejos',
                'city' => 'Cabo San Lucas',
                'state' => '3',
                'postal_code' => '23473',
                'neighborhood' => 'Brisas del Pacifico',
                'latitude' => '22.906510',
                'longitude' => '-109.962970',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '6',
                'status' => '1',
                'created_at' => '2023-07-02 12:53:34',
            ],

             // Propiedad 4 - para Agent 7
             [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Campestre Residencial',
                'property_slug' => 'campestre-residencial',
                'property_code' => 'PC004',
                'property_status' => 'compra',
                'lowest_price' => '4200000',
                'max_price' => '4800000',
                'property_thambnail' => 'upload/property/thambnail/p4t.png',
                'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas',
                'long_descp' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Odio pellentesque diam volutpat commodo sed egestas. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ornare arcu odio ut sem nulla pharetra. Suspendisse interdum consectetur libero id. Sit amet commodo nulla facilisi nullam. Integer vitae justo eget magna fermentum iaculis eu non diam. Nibh ipsum consequat nisl vel pretium lectus. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Pretium vulputate sapien nec sagittis aliquam malesuada. Tortor condimentum lacinia quis vel eros. Nulla facilisi nullam vehicula ipsum. Facilisis magna etiam tempor orci eu lobortis elementum. Sed vulputate odio ut enim blandit. Auctor urna nunc id cursus metus aliquam eleifend mi. Ut sem viverra aliquet eget sit amet tellus. Elit sed vulputate mi sit amet mauris commodo.</p>',
                'bedrooms' => '4',
                'bathrooms' => '2',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'eugenio garza sada #121221, Colonia Condominio Q Campestre Residencial',
                'city' => 'Aguacalientes',
                'state' => '1',
                'postal_code' => '20997',
                'neighborhood' => 'Palo Alto',
                'latitude' => '21.910080',
                'longitude' => '-102.328910',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '7',
                'status' => '1',
                'created_at' => '2023-07-03 12:53:34',
            ],

            // Propiedad 5 - para Agent 2 (Agent)
            [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Golf',
                'property_slug' => 'golf',
                'property_code' => 'PC005',
                'property_status' => 'compra',
                'lowest_price' => '18250000',
                'max_price' => '18500000',
                'property_thambnail' => 'upload/property/thambnail/p5t.png',
                'short_descp' => 'Casa en venta chapultepec, tijuana, baja california 5 recámaras 5 baños 478 m tipo de vivienda: casa tipo de operación: venta superficie total: 408 m $ 18,000,000 mxn descripción casa en venta en una de las zonas más exclusivas y con ubicación privilegiada dentro del corazón de la ciudad de tijuana. esta propiedad ofrece un diseño con un concepto de unidad, espacios abiertos y luminosos que permiten la facilidad de convivencia e integración familiar, así como la funcionalidad de movilidad para personas que tengan dicha necesidad o adultos mayores.',
                'long_descp' => '<p>Casa en venta chapultepec, tijuana, baja california 5 recámaras 5 baños 478 m tipo de vivienda: casa tipo de operación: venta superficie total: 408 m $ 18,000,000 mxn descripción casa en venta en una de las zonas más exclusivas y con ubicación privilegiada dentro del corazón de la ciudad de tijuana. esta propiedad ofrece un diseño con un concepto de unidad, espacios abiertos y luminosos que permiten la facilidad de convivencia e integración familiar, así como la funcionalidad de movilidad para personas que tengan dicha necesidad o adultos mayores. la casa consta de dos plantas, elevador para trasladarse al segundo piso, cuarto de visitas independiente con un baño completo, área de lavado y cuarto de servicio, espacios para almacenamiento en el interior y exterior. esta casa cuenta con espacios muy cómodos y excelentes acabados. planta baja. recibidor, sala, comedor con chimenea. cocina integral equipada. estudio. 1 recamara amplia con baño completo. planta alta 3 recámaras, dos baños completos así como un vestidor en la recámara principal. cuenta con un patio de tamaño mediano. instalaciones especiales como son: aire acondicionado paneles solares cisterna con una capacidad de 12 m3. sistema de purificación y tratamiento de agua. la casa cuenta con: terreno 408 m2 construcción 478 m2 se muestra previa cita. la casa se vende equipada y con el mobiliario mostrado en las fotografías. califica para venta de contado y crédito bancario. informes whatsapp</p>',
                'bedrooms' => '4',
                'bathrooms' => '3',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'Avenida Buenaventura 394 #394, Colonia Campo de Golf, C.P. 22020 ',
                'city' => 'Tijuana',
                'state' => '2',
                'postal_code' => '22020',
                'neighborhood' => 'Avenida Buenaventura',
                'latitude' => '32.506417',
                'longitude' => '-117.006866',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '2',
                'status' => '1',
                'created_at' => '2023-07-01 12:53:34',
            ],

            // Propiedad 6 - para Agent 2 (Agent)
            [
                'ptype_id' => '1',
                'amenities_id' => 'Servicio de Limpieza,Pisos de Madera,Microondas,Estufa,Cancha de Basket Ball',
                'property_name' => 'Cumbre Rubí',
                'property_slug' => 'cumbre-rubi',
                'property_code' => 'PC006',
                'property_status' => 'compra',
                'lowest_price' => '3250000',
                'max_price' => '3380000',
                'property_thambnail' => 'upload/property/thambnail/p6t.png',
                'short_descp' => 'De la tierra 5424 tejamen 22635 tijuana b. ubicadas en tijuana b. en la colonia tejamen. amplias y modernas casas de 2 y 3 recamaras a 5 minutos de zona río y 10 minutos de la garita de san ysidro. privada con acceso controlado. solo 7 casa listas para habitar. entrega en mayo de 2022.',
                'long_descp' => '<p>De la tierra 5424 tejamen 22635 tijuana b. ubicadas en tijuana b. en la colonia tejamen. amplias y modernas casas de 2 y 3 recamaras a 5 minutos de zona río y 10 minutos de la garita de san ysidro. privada con acceso controlado. solo 7 casa listas para habitar. entrega en mayo de 2022. acceso controlado portón y puerta peatonal eléctricos sistema de video vigilancia servicios subterráneos alumbrado público y área verde. ubicadas en calle san ramón de la tierra col. tejamen por blvd. cuauhtémoc sur a 100 metros del colegio juan bosco. se pide 10% de enganchepuede apartar con tan solo $20000 pesos!listas para entregarse! casa de 2 recamaras recamara principal con walkin closet sala comedor y cocina balcón en sala y recamara principal 3 niveles con garaje techado 1 baño completo y 2 medios baños área de lavado boiler y basura patio techado y espacio para asador superficie de 55 m2 de terreno y 117 m2 de construcción requisitos generales cumplir con la edad mínima de 25 y máxima de 65 años. mantener una relación laboral estable (más de un año). tener comprobantes de ingresos. disponer de un historial de crédito positivo. contar con documentación oficial para identificación personal y de domicilio contratar seguro de vida y de daños al inmueble. extranjeros acreditar residencia legal en méxico obtener autorización de la ser constitución de un fideicomiso o sociedad mexicana doble nacionalidad o compra con un familiar mexicano notaria y bancos1.- antecedente de propiedad plano (deslinde catastral) régimen de condominio terminación de obra (c4) *** avalúo libertad de gravámenes fiscales libertad de gravámenes rppc las imágenes mostradas pueden variar a las del producto original. los precios publicados están sujetos a cambio sin previo aviso. el precio publicado no incluye los gastos de escrituración. ¡te llevo a conocerla espero tu llamada!</p>',
                'bedrooms' => '4',
                'bathrooms' => '3',
                'garage' => '1',
                'garage_size' => '155',
                'property_size' => '650',
                'property_video' => null,
                'address' => 'Cumbres del Rubí, Colonia Cumbres del Rubí, C.P. 22635',
                'city' => 'Tijuana',
                'state' => '2',
                'postal_code' => '22635',
                'neighborhood' => 'Cumbres del Rubí',
                'latitude' => '32.484149',
                'longitude' => '-117.022857',
                'google_map' => null,
                'featured' => '1',
                'hot' => '1',
                'agent_id' => '2',
                'status' => '1',
                'created_at' => '2023-07-01 12:53:34',
            ],


         ]);
    }
}
